### ISSUE TITLE
Library size wrong

### ISSUE THREAD

**Issue by PilaScat** [RaunoT/plex-rewind#275] opened 2024-11-30 21:37 UTC
### Plex Rewind Version

v4.4.3

### Description

In dashboard, the size is wrong for all of them, maybe because I have differnet versions for media? 1080p and 4K?
My TV Library is 54TB and it shows 28TB
My Movie Library is 36TB and it shows 10TB

### Steps to reproduce

In dashboard, the size is wrong for all of them

### Screenshots

Movies (Film):
![image](https://github.com/user-attachments/assets/3dfcf99b-5d98-49f9-b431-e73652d88393)
![image](https://github.com/user-attachments/assets/916252d3-da3a-4e6b-99a5-db776601a905)

TV (Serie TV and Anime):
![image](https://github.com/user-attachments/assets/a88066f8-dbb4-42b5-86d4-dd37cb53c522)
![image](https://github.com/user-attachments/assets/2c9489b4-45d7-43c0-957a-b6e34ea8285b)

### Platform

server

### Device

Docker

### Operating System

unRAID

### Browser and version

not depending

**Comment by Cottonsmiles** [comment] 2024-12-03 21:57
I am having the same issue with my dashboard. My movies page shows a very low about of TB and the TV Shows don't show a size at all. This means it shows the incorrect size in the Rewind as well. Running v4.4.3 in Docker on Windows.

**Comment by RaunoT** [comment] 2024-12-04 07:58
@PilaScat and @Cottonsmiles have you verified your library sizes from Tautulli?
You can see this by going to Libraries -> (choose some library) -> Media info -> The size will show on the bottom
<img width="603" alt="image" src="https://github.com/user-attachments/assets/c40a22c7-3a57-4aad-97c3-e1bbabc39567">

Plex Rewind gets all it's info from Tautulli.
Closing as a duplicate of #183

**Closed by RaunoT** 2024-12-04 07:58 UTC
Labels: type:bug, awaiting triage
