### ISSUE TITLE
Plex Directory Size Wrong

### ISSUE THREAD

**Issue by XCrownedClownsX** [RaunoT/plex-rewind#192] opened 2024-07-28 01:36 UTC
### Plex Rewind Version

v2.4.0-develop.6

### Description

Installed via the Unraid container through the app store. Since all my apps are on a 4 TB cache drive, it's only seeing that Plex has an entire size of 4 TB instead of what I know the total size to be around 60 TB on my array. 

Ideally, you could fix it by adding the ability to map another mnt point and point the system that sees the total directory size to that new mount point. 

### Steps to reproduce

Would need an Unraid server, its split between the cache and the array.

### Screenshots

![image](https://github.com/user-attachments/assets/e229715b-2fe4-483b-a222-1ee2ea12a7bc)

### Platform

desktop

### Device

Unraid

### Operating System

Unraid 6.12.11

### Browser and version

Latest version of Chrome.

**Comment by RaunoT** [comment] 2024-07-28 06:58
Duplicate of #183 and #109.

**Closed by RaunoT** 2024-07-28 06:58 UTC
Labels: type:bug
