### ISSUE TITLE
Filesize not shown for TV shows and total Filesize is wrong

### ISSUE THREAD

**Issue by Lucqqq** [RaunoT/plex-rewind#183] opened 2024-07-26 11:46 UTC
### Plex Rewind Version

v2.3.1

### Description

The used storage pace is only shown for movie libraries.
The total Filesize as written on the rewind cards also ignores tv-shows.

Movies on the Dashboard:
![image](https://github.com/user-attachments/assets/eb964e48-4dd7-4585-af2f-b9e45cc1a7ed)
![image](https://github.com/user-attachments/assets/258ade6a-8413-4130-8ab3-17ed10ec9708)

TV-Shows on the Dashboard:
![image](https://github.com/user-attachments/assets/a4644f25-f0c2-41fa-9fd8-848fd48fecb3)
![image](https://github.com/user-attachments/assets/956c6946-1271-43e0-91c0-0492a43a4431)

Rewind Cards:
![image](https://github.com/user-attachments/assets/29f3cfc3-aca7-4d2a-9ae9-4e9384d97924)

### Steps to reproduce

1. Have a movie library
2. have a tv show library
3. see the total amount is wrong

### Platform

desktop

### Device

Notebook

### Operating System

Windows 11

### Browser and version

Firefox 115.13.0esr

**Comment by RaunoT** [comment] 2024-07-26 14:22
Duplicate of #109 

Filesizes are pulled from Tautulli. 

- Tautulli Settings -> General -> Calculate Total File Sizes should be enabled.
- You can refresh library sizes by going to Libraries -> Click on a library -> Media info -> Refresh media info. Note that this might take a while for large libraries with many files. I'm not sure if there's a way to automatically do this for all libraries at a set interval. Unfortunately this is a limitation by Tautulli and there are no plans for Plex Rewind to start regurarly reading the filesystem for these sizes. We will just report what Tautulli says.

The next release will include a toggle to remove displaying of filesizes alltogether, if that's what you're interested in.

**Closed by RaunoT** 2024-07-26 14:22 UTC
Labels: type:bug, awaiting-triage
