### ISSUE TITLE
Sort by plays/views rather than time

### ISSUE THREAD

**Issue by Giffdev** [RaunoT/plex-rewind#229] opened 2024-08-19 20:24 UTC
### Description

Currently, when showing me my "top" movies and shows, it seems to be sorting by total time spent watching it, so a movie like The Godfather with a long runtime shows up even though I've only watched it once.  

### Desired behavior

I think default sorting by number of plays would be most appropriate

**Comment by RaunoT** [comment] 2024-08-19 21:03
Duplicate of #186

**Closed** 2024-08-19 21:03 UTC
Labels: type:enhancement, awaiting triage
