### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PilaScat** [RaunoT/plex-rewind#276] opened 2024-11-30 21:47 UTC
### Description

I know you've already opened an issue and then closed it but it would be great to have a version, in my case in Italian, for non-English users.

### Desired behavior

It would be enough to add support in the app and use a translation platform, so that we users can translate into our languages ​​ourselves

**Comment by RaunoT** [comment] 2024-12-01 10:27
Duplicate of #200

**Closed by RaunoT** 2024-12-01 10:27 UTC
Labels: type:enhancement, awaiting triage
